sudo : required
services: 
  - docker 
beforeInstall:
  - docker build -t jawadmelatyar/docker-react -f Dockerfile.dev . 
script: 
  - docker run jawadmelatyar/docker-react npm run test -- --coverage
